### ISSUE TITLE
Error in tensorflow 0.11.0rc1

### ISSUE THREAD

**Issue by youknowone** [carpedm20/NTM-tensorflow#11]
```
$ python main.py --task copy --is_train True
{'checkpoint_dir': 'checkpoint',
 'controller_layer_size': 1,
 'epoch': 100000,
 'input_dim': 10,
 'is_train': True,
 'max_length': 10,
 'min_length': 1,
 'output_dim': 10,
 'read_head_size': 1,
 'task': 'copy',
 'test_max_length': 120,
 'write_head_size': 1}
 [*] Building a NTM model
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    tf.app.run()
  File "/Volumes/UserSpace/Projects/NTM-tensorflow/.env/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "main.py", line 27, in main
    cell, ntm = copy_train(FLAGS, sess)
  File "/Volumes/UserSpace/Projects/NTM-tensorflow/tasks/copy.py", line 72, in copy_train
    ntm = NTM(cell, sess, config.min_length, config.max_length)
  File "/Volumes/UserSpace/Projects/NTM-tensorflow/ntm.py", line 82, in __init__
    self.build_model(forward_only)
  File "/Volumes/UserSpace/Projects/NTM-tensorflow/ntm.py", line 90, in build_model
    _, prev_state = self.cell(self.start_symbol, state=None)
  File "/Volumes/UserSpace/Projects/NTM-tensorflow/ntm_cell.py", line 62, in __call__
    _, state = self.initial_state()
  File "/Volumes/UserSpace/Projects/NTM-tensorflow/ntm_cell.py", line 288, in initial_state
    squeeze=True, name='read_w_%d' % idx)
  File "/Volumes/UserSpace/Projects/NTM-tensorflow/ops.py", line 109, in Linear
    identity_initializer(tf.cast(range_, tf.float32)))
  File "/Volumes/UserSpace/Projects/NTM-tensorflow/.env/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1022, in get_variable
    custom_getter=custom_getter)
  File "/Volumes/UserSpace/Projects/NTM-tensorflow/.env/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 849, in get_variable
    custom_getter=custom_getter)
  File "/Volumes/UserSpace/Projects/NTM-tensorflow/.env/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 345, in get_variable
    validate_shape=validate_shape)
  File "/Volumes/UserSpace/Projects/NTM-tensorflow/.env/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 330, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/Volumes/UserSpace/Projects/NTM-tensorflow/.env/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 676, in _get_single_variable
    validate_shape=validate_shape)
  File "/Volumes/UserSpace/Projects/NTM-tensorflow/.env/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 215, in __init__
    dtype=dtype)
  File "/Volumes/UserSpace/Projects/NTM-tensorflow/.env/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 288, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/Volumes/UserSpace/Projects/NTM-tensorflow/.env/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 666, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
TypeError: _initializer() got an unexpected keyword argument 'partition_info'
```

**Comment by youknowone** [comment]
@carpedm20 How about to add working tensorflow version to README?
