### ISSUE TITLE
Runtime Error when it is tested for quick copy task

### ISSUE THREAD

**Issue by iliTheFallen** [carpedm20/NTM-tensorflow#24]
Hello,

I am having the following weird exception when I run the script for a quick test (**python main.py --task copy --test_max_length 10**)

`Traceback (most recent call last):
  File "/Users/iliTheFallen/Documents/universityOfHouston/thesis/libs/NTM-tensorflow/main.py", line 72, in <module>
    tf.app.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/Users/iliTheFallen/Documents/universityOfHouston/thesis/libs/NTM-tensorflow/main.py", line 62, in main
    task.run(ntm, FLAGS.test_max_length * 1 / 3, sess)
  File "/Users/iliTheFallen/Documents/universityOfHouston/thesis/libs/NTM-tensorflow/tasks/copy.py", line 18, in run
    seq = generate_copy_sequence(seq_length, ntm.cell.input_dim - 2)
  File "/Users/iliTheFallen/Documents/universityOfHouston/thesis/libs/NTM-tensorflow/tasks/copy.py", line 107, in generate_copy_sequence
    seq = np.zeros([length, bits + 2], dtype=np.float32)
TypeError: 'float' object cannot be interpreted as an integer`

**Comment by carpedm20** [comment]
When I just downloaded the code and copy and pasted the command `python main.py --task copy --test_max_length 10`, there was no error as you posted. Did you try the lastest code?

**Comment by iliTheFallen** [comment]
Yeah that is what I did. I think the 'length'  parameter passed to 'generate_copy_sequence' method for the first run is 3.3333. That is what pycharm debugger tells.

**Comment by carpedm20** [comment]
Ah, you are using python3. I'll fix this anyway.
