### ISSUE TITLE
checkpoint_dir not found when test_max_length is greater than max_length

### ISSUE THREAD

**Issue by ghost** [carpedm20/NTM-tensorflow#9]
For example, assume max_length is 10 and test_max_length is 20:

```
Percent: [####################] 100.00% Finished.
 [*] Build a NTM model finished
 [*] Reading checkpoints...
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "main.py", line 38, in main
    ntm.load(FLAGS.checkpoint_dir, 'copy')
  File "/root/NTM-tensorflow/ntm.py", line 257, in load
    raise Exception(" [!] Testing, but %s not found" % checkpoint_dir)
Exception:  [!] Testing, but checkpoint/copy_20 not found
```

Make a symbolic link from checkpoint/copy_10 to checkpoint/copy_20 works around the problem.

Nice job, thank you!

**Comment by linamede** [comment]
When running the  test  quick copy task:

$ python main.py --task copy --test_max_length 10

it gives the  error "Restore called with invalid save path" . I have not changed anything in the provided code, and as I can see, the checkpoint exists in the required path "checkpoint/copy_10/NTM-copy_copy.model-3402". Anyone faced the same problem? 

I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
{'checkpoint_dir': 'checkpoint',
 'continue_train': None,
 'controller_dim': 100,
 'controller_layer_size': 1,
 'epoch': 100000,
 'input_dim': 10,
 'is_train': False,
 'max_length': 10,
 'min_length': 1,
 'output_dim': 10,
 'read_head_size': 1,
 'task': 'copy',
 'test_max_length': 10,
 'write_head_size': 1}
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties: 
name: GeForce GTX 960
major: 5 minor: 2 memoryClockRate (GHz) 1.253
pciBusID 0000:01:00.0
Total memory: 3.94GiB
Free memory: 263.00MiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 960, pci bus id: 0000:01:00.0)
 [*] Building a NTM model

Percent: [##                  ] 10.00% 
Percent: [####                ] 20.00% 
Percent: [######              ] 30.00% 
Percent: [########            ] 40.00% 
Percent: [##########          ] 50.00% 
Percent: [############        ] 60.00% 
Percent: [##############      ] 70.00% 
Percent: [################    ] 80.00% 
Percent: [##################  ] 90.00% 
Percent: [####################] 100.00% Finished.
 [*] Build a NTM model finished
 [*] Reading checkpoints...
task_dir copy_10
checkpoint_dir checkpoint/copy_10
Traceback (most recent call last):
  File "/home/user/Desktop/NTM-tensorflow-master/main.py", line 72, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/user/Desktop/NTM-tensorflow-master/main.py", line 59, in main
    ntm.load(FLAGS.checkpoint_dir, FLAGS.task)
  File "/home/user/Desktop/NTM-tensorflow-master/ntm.py", line 268, in load
    self.saver.restore(self.sess, os.path.join(checkpoint_dir, ckpt_name))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1342, in restore
    "File path is: %r" % (save_path, file_path))
ValueError: Restore called with invalid save path: u'checkpoint/copy_10/NTM-copy_copy.model-3402'. File path is: u'checkpoint/copy_10/NTM-copy_copy.model-3402'
[Finished in 31.5s with exit code 1]
